- hosts: all
  gather_facts: true
  become: yes
  become_user: root
  roles:
#     - nic_config
    - daq
    - snort
    - barnyard2
    - pulledpork
    - crontab
    - mysql
    - snorby
    - passenger
    - alerts
    - supress_events
